-- homework5-ddl.sql

-- task 1
-- store your drop table statements in this block
drop table if exists raw_country;
drop table if exists country;

-- task 2 - Create "raw_country" table
-- label the columns using the following schema:
--  raw_country(country_code,
--              country_short_name,
--              country_full_name,
--              country_abbr,
--              country_region,
--              country_income_category,
--              country_wb_abbr,
--              country_count)
-- Assign appropriate data types.
-- Assign an appropriate primary key.
-- Set default value to country_count 1
drop table if exists raw_country; 
create table raw_country(country_code varchar(255),
              country_short_name varchar(255),
              country_full_name varchar(255),
              country_abbr varchar(255),
              country_region varchar(255),
              country_income_category varchar(255),
              country_wb_abbr varchar(255),
              country_count int default 1,
              primary key (country_code)
              );
              


-- task 3 - Insert records into raw_country table using data from CSV file
-- DATA PIPELINE TRICK:
--   - create the appropriate INSERT command header
--   - THEN, use a spreadsheet to turn each row of the CSV file into 
--     an appropriately formatted VALUES statement,
--   - THEN, copy and paste the ENTIRE block of values into the DDL file below.
--   - This trick works with just about ANY table!
--   - Watch out for single apostrophes, they need to be manually converted to ''
--     take advantage of the VSCODE colors.
insert into raw_country(country_code,
              country_short_name,
              country_full_name,
              country_abbr,
              country_region,
              country_income_category,
              country_wb_abbr,
              country_count) values 
  ("ABW","Aruba","Aruba","AW","Latin America & Caribbean","High income","AW",1),
  ("AFE","Africa Eastern and Southern","Africa Eastern and Southern","ZH","","","ZH",1),
  ("AFG","Afghanistan","Islamic State of Afghanistan","AF","South Asia","Low income","AF",1),
  ("AFW","Africa Western and Central","Africa Western and Central","ZI","","","ZI",1),
  ("AGO","Angola","People's Republic of Angola","AO","Sub-Saharan Africa","Lower middle income","AO",1),
  ("ALB","Albania","Republic of Albania","AL","Europe & Central Asia","Upper middle income","AL",1),
  ("AND","Andorra","Principality of Andorra","AD","Europe & Central Asia","High income","AD",1),
  ("ARB","Arab World","Arab World","1A","","","1A",1),
  ("ARE","United Arab Emirates","United Arab Emirates","AE","Middle East & North Africa","High income","AE",1),
  ("ARG","Argentina","Argentine Republic","AR","Latin America & Caribbean","Upper middle income","AR",1),
  ("ARM","Armenia","Republic of Armenia","AM","Europe & Central Asia","Upper middle income","AM",1),
  ("ASM","American Samoa","American Samoa","AS","East Asia & Pacific","Upper middle income","AS",1),
  ("ATG","Antigua and Barbuda","Antigua and Barbuda","AG","Latin America & Caribbean","High income","AG",1),
  ("AUS","Australia","Commonwealth of Australia","AU","East Asia & Pacific","High income","AU",1),
  ("AUT","Austria","Republic of Austria","AT","Europe & Central Asia","High income","AT",1),
  ("AZE","Azerbaijan","Republic of Azerbaijan","AZ","Europe & Central Asia","Upper middle income","AZ",1),
  ("BDI","Burundi","Republic of Burundi","BI","Sub-Saharan Africa","Low income","BI",1),
  ("BEL","Belgium","Kingdom of Belgium","BE","Europe & Central Asia","High income","BE",1),
  ("BEN","Benin","Republic of Benin","BJ","Sub-Saharan Africa","Lower middle income","BJ",1),
  ("BFA","Burkina Faso","Burkina Faso","BF","Sub-Saharan Africa","Low income","BF",1),
  ("BGD","Bangladesh","People's Republic of Bangladesh","BD","South Asia","Lower middle income","BD",1),
  ("BGR","Bulgaria","Republic of Bulgaria","BG","Europe & Central Asia","Upper middle income","BG",1),
  ("BHR","Bahrain","Kingdom of Bahrain","BH","Middle East & North Africa","High income","BH",1),
  ("BHS","The Bahamas","Commonwealth of The Bahamas","BS","Latin America & Caribbean","High income","BS",1),
  ("BIH","Bosnia and Herzegovina","Bosnia and Herzegovina","BA","Europe & Central Asia","Upper middle income","BA",1),
  ("BLR","Belarus","Republic of Belarus","BY","Europe & Central Asia","Upper middle income","BY",1),
  ("BLZ","Belize","Belize","BZ","Latin America & Caribbean","Upper middle income","BZ",1),
  ("BMU","Bermuda","The Bermudas","BM","North America","High income","BM",1),
  ("BOL","Bolivia","Plurinational State of Bolivia","BO","Latin America & Caribbean","Lower middle income","BO",1),
  ("BRA","Brazil","Federative Republic of Brazil","BR","Latin America & Caribbean","Upper middle income","BR",1),
  ("BRB","Barbados","Barbados","BB","Latin America & Caribbean","High income","BB",1),
  ("BRN","Brunei","Brunei Darussalam","BN","East Asia & Pacific","High income","BN",1),
  ("BTN","Bhutan","Kingdom of Bhutan","BT","South Asia","Lower middle income","BT",1),
  ("BWA","Botswana","Republic of Botswana","BW","Sub-Saharan Africa","Upper middle income","BW",1),
  ("CAF","Central African Republic","Central African Republic","CF","Sub-Saharan Africa","Low income","CF",1),
  ("CAN","Canada","Canada","CA","North America","High income","CA",1),
  ("CEB","Central Europe and the Baltics","Central Europe and the Baltics","B8","","","B8",1),
  ("CHE","Switzerland","Switzerland","CH","Europe & Central Asia","High income","CH",1),
  ("CHI","Channel Islands","Channel Islands","","Europe & Central Asia","High income","JG",1),
  ("CHL","Chile","Republic of Chile","CL","Latin America & Caribbean","High income","CL",1),
  ("CHN","China","People's Republic of China","CN","East Asia & Pacific","Upper middle income","CN",1),
  ("CIV","Côte d'Ivoire","Republic of Côte d'Ivoire","CI","Sub-Saharan Africa","Lower middle income","CI",1),
  ("CMR","Cameroon","Republic of Cameroon","CM","Sub-Saharan Africa","Lower middle income","CM",1),
  ("COD","Dem. Rep. Congo","Democratic Republic of the Congo","CD","Sub-Saharan Africa","Low income","ZR",1),
  ("COG","Congo","Republic of Congo","CG","Sub-Saharan Africa","Lower middle income","CG",1),
  ("COL","Colombia","Republic of Colombia","CO","Latin America & Caribbean","Upper middle income","CO",1),
  ("COM","Comoros","Union of the Comoros","KM","Sub-Saharan Africa","Lower middle income","KM",1),
  ("CPV","Cabo Verde","Republic of Cabo Verde","CV","Sub-Saharan Africa","Lower middle income","CV",1),
  ("CRI","Costa Rica","Republic of Costa Rica","CR","Latin America & Caribbean","Upper middle income","CR",1),
  ("CSS","Caribbean small states","Caribbean small states","S3","","","S3",1),
  ("CUB","Cuba","Republic of Cuba","CU","Latin America & Caribbean","Upper middle income","CU",1),
  ("CUW","Curaçao","Curaçao","CW","Latin America & Caribbean","High income","CW",1),
  ("CYM","Cayman Islands","Cayman Islands","KY","Latin America & Caribbean","High income","KY",1),
  ("CYP","Cyprus","Republic of Cyprus","CY","Europe & Central Asia","High income","CY",1),
  ("CZE","Czech Republic","Czech Republic","CZ","Europe & Central Asia","High income","CZ",1),
  ("DEU","Germany","Federal Republic of Germany","DE","Europe & Central Asia","High income","DE",1),
  ("DJI","Djibouti","Republic of Djibouti","DJ","Middle East & North Africa","Lower middle income","DJ",1),
  ("DMA","Dominica","Commonwealth of Dominica","DM","Latin America & Caribbean","Upper middle income","DM",1),
  ("DNK","Denmark","Kingdom of Denmark","DK","Europe & Central Asia","High income","DK",1),
  ("DOM","Dominican Republic","Dominican Republic","DO","Latin America & Caribbean","Upper middle income","DO",1),
  ("DZA","Algeria","People's Democratic Republic of Algeria","DZ","Middle East & North Africa","Lower middle income","DZ",1),
  ("EAP","East Asia & Pacific (excluding high income)","East Asia & Pacific (excluding high income)","4E","","","4E",1),
  ("EAR","Early-demographic dividend","Early-demographic dividend","V2","","","V2",1),
  ("EAS","East Asia & Pacific","East Asia & Pacific","Z4","","","Z4",1),
  ("ECA","Europe & Central Asia (excluding high income)","Europe & Central Asia (excluding high income)","7E","","","7E",1),
  ("ECS","Europe & Central Asia","Europe & Central Asia","Z7","","","Z7",1),
  ("ECU","Ecuador","Republic of Ecuador","EC","Latin America & Caribbean","Upper middle income","EC",1),
  ("EGY","Egypt","Arab Republic of Egypt","EG","Middle East & North Africa","Lower middle income","EG",1),
  ("EMU","Euro area","Euro area","XC","","","XC",1),
  ("ERI","Eritrea","State of Eritrea","ER","Sub-Saharan Africa","Low income","ER",1),
  ("ESP","Spain","Kingdom of Spain","ES","Europe & Central Asia","High income","ES",1),
  ("EST","Estonia","Republic of Estonia","EE","Europe & Central Asia","High income","EE",1),
  ("ETH","Ethiopia","Federal Democratic Republic of Ethiopia","ET","Sub-Saharan Africa","Low income","ET",1),
  ("EUU","European Union","European Union","EU","","","EU",1),
  ("FCS","Fragile and conflict affected situations","Fragile and conflict affected situations","F1","","","F1",1),
  ("FIN","Finland","Republic of Finland","FI","Europe & Central Asia","High income","FI",1),
  ("FJI","Fiji","Republic of Fiji","FJ","East Asia & Pacific","Upper middle income","FJ",1),
  ("FRA","France","French Republic","FR","Europe & Central Asia","High income","FR",1),
  ("FRO","Faroe Islands","Faroe Islands","FO","Europe & Central Asia","High income","FO",1),
  ("FSM","Micronesia","Federated States of Micronesia","FM","East Asia & Pacific","Lower middle income","FM",1),
  ("GAB","Gabon","Gabonese Republic","GA","Sub-Saharan Africa","Upper middle income","GA",1),
  ("GBR","United Kingdom","United Kingdom of Great Britain and Northern Ireland","GB","Europe & Central Asia","High income","GB",1),
  ("GEO","Georgia","Georgia","GE","Europe & Central Asia","Upper middle income","GE",1),
  ("GHA","Ghana","Republic of Ghana","GH","Sub-Saharan Africa","Lower middle income","GH",1),
  ("GIB","Gibraltar","Gibraltar","GI","Europe & Central Asia","High income","GI",1),
  ("GIN","Guinea","Republic of Guinea","GN","Sub-Saharan Africa","Low income","GN",1),
  ("GMB","The Gambia","Republic of The Gambia","GM","Sub-Saharan Africa","Low income","GM",1),
  ("GNB","Guinea-Bissau","Republic of Guinea-Bissau","GW","Sub-Saharan Africa","Low income","GW",1),
  ("GNQ","Equatorial Guinea","Republic of Equatorial Guinea","GQ","Sub-Saharan Africa","Upper middle income","GQ",1),
  ("GRC","Greece","Hellenic Republic","GR","Europe & Central Asia","High income","GR",1),
  ("GRD","Grenada","Grenada","GD","Latin America & Caribbean","Upper middle income","GD",1),
  ("GRL","Greenland","Greenland","GL","Europe & Central Asia","High income","GL",1),
  ("GTM","Guatemala","Republic of Guatemala","GT","Latin America & Caribbean","Upper middle income","GT",1),
  ("GUM","Guam","Guam","GU","East Asia & Pacific","High income","GU",1),
  ("GUY","Guyana","Co-operative Republic of Guyana","GY","Latin America & Caribbean","Upper middle income","GY",1),
  ("HIC","High income","High income","XD","","","XD",1),
  ("HKG","Hong Kong SAR, China","Hong Kong Special Administrative Region of the People's Republic of China","HK","East Asia & Pacific","High income","HK",1),
  ("HND","Honduras","Republic of Honduras","HN","Latin America & Caribbean","Lower middle income","HN",1),
  ("HPC","Heavily indebted poor countries (HIPC)","Heavily indebted poor countries (HIPC)","XE","","","XE",1),
  ("HRV","Croatia","Republic of Croatia","HR","Europe & Central Asia","High income","HR",1),
  ("HTI","Haiti","Republic of Haiti","HT","Latin America & Caribbean","Lower middle income","HT",1),
  ("HUN","Hungary","Hungary","HU","Europe & Central Asia","High income","HU",1),
  ("IBD","IBRD only","IBRD only","XF","","","XF",1),
  ("IBT","IDA & IBRD total","IDA & IBRD total","ZT","","","ZT",1),
  ("IDA","IDA total","IDA total","XG","","","XG",1),
  ("IDB","IDA blend","IDA blend","XH","","","XH",1),
  ("IDN","Indonesia","Republic of Indonesia","ID","East Asia & Pacific","Lower middle income","ID",1),
  ("IDX","IDA only","IDA only","XI","","","XI",1),
  ("IMN","Isle of Man","Isle of Man","IM","Europe & Central Asia","High income","IM",1),
  ("IND","India","Republic of India","IN","South Asia","Lower middle income","IN",1),
  ("IRL","Ireland","Ireland","IE","Europe & Central Asia","High income","IE",1),
  ("IRN","Iran","Islamic Republic of Iran","IR","Middle East & North Africa","Lower middle income","IR",1),
  ("IRQ","Iraq","Republic of Iraq","IQ","Middle East & North Africa","Upper middle income","IQ",1),
  ("ISL","Iceland","Republic of Iceland","IS","Europe & Central Asia","High income","IS",1),
  ("ISR","Israel","State of Israel","IL","Middle East & North Africa","High income","IL",1),
  ("ITA","Italy","Italian Republic","IT","Europe & Central Asia","High income","IT",1),
  ("JAM","Jamaica","Jamaica","JM","Latin America & Caribbean","Upper middle income","JM",1),
  ("JOR","Jordan","Hashemite Kingdom of Jordan","JO","Middle East & North Africa","Upper middle income","JO",1),
  ("JPN","Japan","Japan","JP","East Asia & Pacific","High income","JP",1),
  ("KAZ","Kazakhstan","Republic of Kazakhstan","KZ","Europe & Central Asia","Upper middle income","KZ",1),
  ("KEN","Kenya","Republic of Kenya","KE","Sub-Saharan Africa","Lower middle income","KE",1),
  ("KGZ","Kyrgyz Republic","Kyrgyz Republic","KG","Europe & Central Asia","Lower middle income","KG",1),
  ("KHM","Cambodia","Kingdom of Cambodia","KH","East Asia & Pacific","Lower middle income","KH",1),
  ("KIR","Kiribati","Republic of Kiribati","KI","East Asia & Pacific","Lower middle income","KI",1),
  ("KNA","St. Kitts and Nevis","St. Kitts and Nevis","KN","Latin America & Caribbean","High income","KN",1),
  ("KOR","Korea","Republic of Korea","KR","East Asia & Pacific","High income","KR",1),
  ("KWT","Kuwait","State of Kuwait","KW","Middle East & North Africa","High income","KW",1),
  ("LAC","Latin America & Caribbean (excluding high income)","Latin America & Caribbean (excluding high income)","XJ","","","XJ",1),
  ("LAO","Lao PDR","Lao People's Democratic Republic","LA","East Asia & Pacific","Lower middle income","LA",1),
  ("LBN","Lebanon","Lebanese Republic","LB","Middle East & North Africa","Lower middle income","LB",1),
  ("LBR","Liberia","Republic of Liberia","LR","Sub-Saharan Africa","Low income","LR",1),
  ("LBY","Libya","Socialist People's Libyan Arab Jamahiriya","LY","Middle East & North Africa","Upper middle income","LY",1),
  ("LCA","St. Lucia","St. Lucia","LC","Latin America & Caribbean","Upper middle income","LC",1),
  ("LCN","Latin America & Caribbean","Latin America & Caribbean","ZJ","","","ZJ",1),
  ("LDC","Least developed countries: UN classification","Least developed countries: UN classification","XL","","","XL",1),
  ("LIC","Low income","Low income","XM","","","XM",1),
  ("LIE","Liechtenstein","Principality of Liechtenstein","LI","Europe & Central Asia","High income","LI",1),
  ("LKA","Sri Lanka","Democratic Socialist Republic of Sri Lanka","LK","South Asia","Lower middle income","LK",1),
  ("LMC","Lower middle income","Lower middle income","XN","","","XN",1),
  ("LMY","Low & middle income","Low & middle income","XO","","","XO",1),
  ("LSO","Lesotho","Kingdom of Lesotho","LS","Sub-Saharan Africa","Lower middle income","LS",1),
  ("LTE","Late-demographic dividend","Late-demographic dividend","V3","","","V3",1),
  ("LTU","Lithuania","Republic of Lithuania","LT","Europe & Central Asia","High income","LT",1),
  ("LUX","Luxembourg","Grand Duchy of Luxembourg","LU","Europe & Central Asia","High income","LU",1),
  ("LVA","Latvia","Republic of Latvia","LV","Europe & Central Asia","High income","LV",1),
  ("MAC","Macao SAR, China","Macao Special Administrative Region of the People's Republic of China","MO","East Asia & Pacific","High income","MO",1),
  ("MAF","St. Martin (French part)","St. Martin (French part)","MF","Latin America & Caribbean","High income","MF",1),
  ("MAR","Morocco","Kingdom of Morocco","MA","Middle East & North Africa","Lower middle income","MA",1),
  ("MCO","Monaco","Principality of Monaco","MC","Europe & Central Asia","High income","MC",1),
  ("MDA","Moldova","Republic of Moldova","MD","Europe & Central Asia","Upper middle income","MD",1),
  ("MDG","Madagascar","Republic of Madagascar","MG","Sub-Saharan Africa","Low income","MG",1),
  ("MDV","Maldives","Republic of Maldives","MV","South Asia","Upper middle income","MV",1),
  ("MEA","Middle East & North Africa","Middle East & North Africa","ZQ","","","ZQ",1),
  ("MEX","Mexico","United Mexican States","MX","Latin America & Caribbean","Upper middle income","MX",1),
  ("MHL","Marshall Islands","Republic of the Marshall Islands","MH","East Asia & Pacific","Upper middle income","MH",1),
  ("MIC","Middle income","Middle income","XP","","","XP",1),
  ("MKD","North Macedonia","Republic of North Macedonia","MK","Europe & Central Asia","Upper middle income","MK",1),
  ("MLI","Mali","Republic of Mali","ML","Sub-Saharan Africa","Low income","ML",1),
  ("MLT","Malta","Republic of Malta","MT","Middle East & North Africa","High income","MT",1),
  ("MMR","Myanmar","Republic of the Union of Myanmar","MM","East Asia & Pacific","Lower middle income","MM",1),
  ("MNA","Middle East & North Africa (excluding high income)","Middle East & North Africa (excluding high income)","XQ","","","XQ",1),
  ("MNE","Montenegro","Montenegro","ME","Europe & Central Asia","Upper middle income","ME",1),
  ("MNG","Mongolia","Mongolia","MN","East Asia & Pacific","Lower middle income","MN",1),
  ("MNP","Northern Mariana Islands","Commonwealth of the Northern Mariana Islands","MP","East Asia & Pacific","High income","MP",1),
  ("MOZ","Mozambique","Republic of Mozambique","MZ","Sub-Saharan Africa","Low income","MZ",1),
  ("MRT","Mauritania","Islamic Republic of Mauritania","MR","Sub-Saharan Africa","Lower middle income","MR",1),
  ("MUS","Mauritius","Republic of Mauritius","MU","Sub-Saharan Africa","Upper middle income","MU",1),
  ("MWI","Malawi","Republic of Malawi","MW","Sub-Saharan Africa","Low income","MW",1),
  ("MYS","Malaysia","Malaysia","MY","East Asia & Pacific","Upper middle income","MY",1),
  ("NAC","North America","North America","XU","","","XU",1),
  ("NAM","Namibia","Republic of Namibia","NA","Sub-Saharan Africa","Upper middle income","NA",1),
  ("NCL","New Caledonia","New Caledonia","NC","East Asia & Pacific","High income","NC",1),
  ("NER","Niger","Republic of Niger","NE","Sub-Saharan Africa","Low income","NE",1),
  ("NGA","Nigeria","Federal Republic of Nigeria","NG","Sub-Saharan Africa","Lower middle income","NG",1),
  ("NIC","Nicaragua","Republic of Nicaragua","NI","Latin America & Caribbean","Lower middle income","NI",1),
  ("NLD","Netherlands","Kingdom of the Netherlands","NL","Europe & Central Asia","High income","NL",1),
  ("NOR","Norway","Kingdom of Norway","NO","Europe & Central Asia","High income","NO",1),
  ("NPL","Nepal","Nepal","NP","South Asia","Lower middle income","NP",1),
  ("NRU","Nauru","Republic of Nauru","NR","East Asia & Pacific","High income","NR",1),
  ("NZL","New Zealand","New Zealand","NZ","East Asia & Pacific","High income","NZ",1),
  ("OED","OECD members","OECD members","OE","","","OE",1),
  ("OMN","Oman","Sultanate of Oman","OM","Middle East & North Africa","High income","OM",1),
  ("OSS","Other small states","Other small states","S4","","","S4",1),
  ("PAK","Pakistan","Islamic Republic of Pakistan","PK","South Asia","Lower middle income","PK",1),
  ("PAN","Panama","Republic of Panama","PA","Latin America & Caribbean","High income","PA",1),
  ("PER","Peru","Republic of Peru","PE","Latin America & Caribbean","Upper middle income","PE",1),
  ("PHL","Philippines","Republic of the Philippines","PH","East Asia & Pacific","Lower middle income","PH",1),
  ("PLW","Palau","Republic of Palau","PW","East Asia & Pacific","Upper middle income","PW",1),
  ("PNG","Papua New Guinea","The Independent State of Papua New Guinea","PG","East Asia & Pacific","Lower middle income","PG",1),
  ("POL","Poland","Republic of Poland","PL","Europe & Central Asia","High income","PL",1),
  ("PRE","Pre-demographic dividend","Pre-demographic dividend","V1","","","V1",1),
  ("PRI","Puerto Rico","Puerto Rico","PR","Latin America & Caribbean","High income","PR",1),
  ("PRK","Dem. People's Rep. Korea","Democratic People's Republic of Korea","KP","East Asia & Pacific","Low income","KP",1),
  ("PRT","Portugal","Portuguese Republic","PT","Europe & Central Asia","High income","PT",1),
  ("PRY","Paraguay","Republic of Paraguay","PY","Latin America & Caribbean","Upper middle income","PY",1),
  ("PSE","West Bank and Gaza","West Bank and Gaza","PS","Middle East & North Africa","Lower middle income","GZ",1),
  ("PSS","Pacific island small states","Pacific island small states","S2","","","S2",1),
  ("PST","Post-demographic dividend","Post-demographic dividend","V4","","","V4",1),
  ("PYF","French Polynesia","French Polynesia","PF","East Asia & Pacific","High income","PF",1),
  ("QAT","Qatar","State of Qatar","QA","Middle East & North Africa","High income","QA",1),
  ("ROU","Romania","Romania","RO","Europe & Central Asia","High income","RO",1),
  ("RUS","Russia","Russian Federation","RU","Europe & Central Asia","Upper middle income","RU",1),
  ("RWA","Rwanda","Republic of Rwanda","RW","Sub-Saharan Africa","Low income","RW",1),
  ("SAS","South Asia","South Asia","8S","","","8S",1),
  ("SAU","Saudi Arabia","Kingdom of Saudi Arabia","SA","Middle East & North Africa","High income","SA",1),
  ("SDN","Sudan","Republic of the Sudan","SD","Sub-Saharan Africa","Low income","SD",1),
  ("SEN","Senegal","Republic of Senegal","SN","Sub-Saharan Africa","Lower middle income","SN",1),
  ("SGP","Singapore","Republic of Singapore","SG","East Asia & Pacific","High income","SG",1),
  ("SLB","Solomon Islands","Solomon Islands","SB","East Asia & Pacific","Lower middle income","SB",1),
  ("SLE","Sierra Leone","Republic of Sierra Leone","SL","Sub-Saharan Africa","Low income","SL",1),
  ("SLV","El Salvador","Republic of El Salvador","SV","Latin America & Caribbean","Lower middle income","SV",1),
  ("SMR","San Marino","Republic of San Marino","SM","Europe & Central Asia","High income","SM",1),
  ("SOM","Somalia","Somali Democratic Republic","SO","Sub-Saharan Africa","Low income","SO",1),
  ("SRB","Serbia","Republic of Serbia","RS","Europe & Central Asia","Upper middle income","YF",1),
  ("SSA","Sub-Saharan Africa (excluding high income)","Sub-Saharan Africa (excluding high income)","ZF","","","ZF",1),
  ("SSD","South Sudan","Republic of South Sudan","SS","Sub-Saharan Africa","Low income","SS",1),
  ("SSF","Sub-Saharan Africa","Sub-Saharan Africa","ZG","","","ZG",1),
  ("SST","Small states","Small states","S1","","","S1",1),
  ("STP","São Tomé and Principe","Democratic Republic of São Tomé and Principe","ST","Sub-Saharan Africa","Lower middle income","ST",1),
  ("SUR","Suriname","Republic of Suriname","SR","Latin America & Caribbean","Upper middle income","SR",1),
  ("SVK","Slovak Republic","Slovak Republic","SK","Europe & Central Asia","High income","SK",1),
  ("SVN","Slovenia","Republic of Slovenia","SI","Europe & Central Asia","High income","SI",1),
  ("SWE","Sweden","Kingdom of Sweden","SE","Europe & Central Asia","High income","SE",1),
  ("SWZ","Eswatini","Kingdom of Eswatini","SZ","Sub-Saharan Africa","Lower middle income","SZ",1),
  ("SXM","Sint Maarten (Dutch part)","Sint Maarten (Dutch part)","SX","Latin America & Caribbean","High income","SX",1),
  ("SYC","Seychelles","Republic of Seychelles","SC","Sub-Saharan Africa","High income","SC",1),
  ("SYR","Syrian Arab Republic","Syrian Arab Republic","SY","Middle East & North Africa","Low income","SY",1),
  ("TCA","Turks and Caicos Islands","Turks and Caicos Islands","TC","Latin America & Caribbean","High income","TC",1),
  ("TCD","Chad","Republic of Chad","TD","Sub-Saharan Africa","Low income","TD",1),
  ("TEA","East Asia & Pacific (IDA & IBRD)","East Asia & Pacific (IDA & IBRD)","T4","","","T4",1),
  ("TEC","Europe & Central Asia (IDA & IBRD)","Europe & Central Asia (IDA & IBRD)","T7","","","T7",1),
  ("TGO","Togo","Republic of Togo","TG","Sub-Saharan Africa","Low income","TG",1),
  ("THA","Thailand","Kingdom of Thailand","TH","East Asia & Pacific","Upper middle income","TH",1),
  ("TJK","Tajikistan","Republic of Tajikistan","TJ","Europe & Central Asia","Lower middle income","TJ",1),
  ("TKM","Turkmenistan","Turkmenistan","TM","Europe & Central Asia","Upper middle income","TM",1),
  ("TLA","Latin America & Caribbean (IDA & IBRD)","Latin America & Caribbean (IDA & IBRD)","T2","","","T2",1),
  ("TLS","Timor-Leste","Democratic Republic of Timor-Leste","TL","East Asia & Pacific","Lower middle income","TP",1),
  ("TMN","Middle East & North Africa (IDA & IBRD)","Middle East & North Africa (IDA & IBRD)","T3","","","T3",1),
  ("TON","Tonga","Kingdom of Tonga","TO","East Asia & Pacific","Upper middle income","TO",1),
  ("TSA","South Asia (IDA & IBRD)","South Asia (IDA & IBRD)","T5","","","T5",1),
  ("TSS","Sub-Saharan Africa (IDA & IBRD)","Sub-Saharan Africa (IDA & IBRD)","T6","","","T6",1),
  ("TTO","Trinidad and Tobago","Republic of Trinidad and Tobago","TT","Latin America & Caribbean","High income","TT",1),
  ("TUN","Tunisia","Republic of Tunisia","TN","Middle East & North Africa","Lower middle income","TN",1),
  ("TUR","Türkiye","Republic of Türkiye","TR","Europe & Central Asia","Upper middle income","TR",1),
  ("TUV","Tuvalu","Tuvalu","TV","East Asia & Pacific","Upper middle income","TV",1),
  ("TZA","Tanzania","United Republic of Tanzania","TZ","Sub-Saharan Africa","Lower middle income","TZ",1),
  ("UGA","Uganda","Republic of Uganda","UG","Sub-Saharan Africa","Low income","UG",1),
  ("UKR","Ukraine","Ukraine","UA","Europe & Central Asia","Lower middle income","UA",1),
  ("UMC","Upper middle income","Upper middle income","XT","","","XT",1),
  ("URY","Uruguay","Oriental Republic of Uruguay","UY","Latin America & Caribbean","High income","UY",1),
  ("USA","United States","United States of America","US","North America","High income","US",1),
  ("UZB","Uzbekistan","Republic of Uzbekistan","UZ","Europe & Central Asia","Lower middle income","UZ",1),
  ("VCT","St. Vincent and the Grenadines","St. Vincent and the Grenadines","VC","Latin America & Caribbean","Upper middle income","VC",1),
  ("VEN","Venezuela","República Bolivariana de Venezuela","VE","Latin America & Caribbean","","VE",1),
  ("VGB","British Virgin Islands","British Virgin Islands","VG","Latin America & Caribbean","High income","VG",1),
  ("VIR","Virgin Islands","Virgin Islands of the United States","VI","Latin America & Caribbean","High income","VI",1),
  ("VNM","Vietnam","Socialist Republic of Vietnam","VN","East Asia & Pacific","Lower middle income","VN",1),
  ("VUT","Vanuatu","Republic of Vanuatu","VU","East Asia & Pacific","Lower middle income","VU",1),
  ("WLD","World","World","1W","","","1W",1),
  ("WSM","Samoa","Samoa","WS","East Asia & Pacific","Lower middle income","WS",1),
  ("XKX","Kosovo","Republic of Kosovo","XK","Europe & Central Asia","Upper middle income","XK",1),
  ("YEM","Yemen","Republic of Yemen","YE","Middle East & North Africa","Low income","RY",1),
  ("ZAF","South Africa","Republic of South Africa","ZA","Sub-Saharan Africa","Upper middle income","ZA",1),
  ("ZMB","Zambia","Republic of Zambia","ZM","Sub-Saharan Africa","Low income","ZM",1),
  ("ZWE","Zimbabwe","Republic of Zimbabwe","ZW","Sub-Saharan Africa","Lower middle income","ZW",1)
  ;

-- task 4 - create COUNTRY table
-- After doing the first few tasks in the DML file, write a 
-- CREATE TABLE with INSERT command, filling only with real country data
drop table if exists COUNTRY;
CREATE TABLE COUNTRY
SELECT 
    * 
FROM 
    raw_country 
where 
    country_region <> '';

DESCRIBE COUNTRY;



